services:
  server:
    image: nicolausnl/windstore-server:latest
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules

    environment:
      DATABASE_URL: "postgresql://postgres:123@postgres:5432/windstore"

    depends_on:
      - postgres

  client:
    image: nicolausnl/windstore-client:latest
    build: ./client
    ports:
      - "5173:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"

  postgres:
    image: postgres:17
    container_name: windstore-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: windstore

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
